version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0.33
    container_name: db
    ports:
      - "3036:3036"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db_node
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql

  node:
    build: ./node
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
    

